POST http://192.168.0.37:3000/products/add-product
Content-Type: application/json

{
"barcode": "0014100054122"
}
### 
GET http://localhost:3000/products/

### 
GET http://localhost:3000/inventory/Snacks

### 
DELETE http://localhost:3000/inventory/672edb6a2aea1d00c27e319b

### 
GET http://localhost:3000/recipes/all